const responseMessage = {
  NULL_VALUE: '필요한 값이 없습니다.',
  OUT_OF_VALUE: '파라미터 값이 잘못 되었습니다.',
  SIGN_UP_SUCCESS: '회원가입 성공',
  SIGN_UP_FAIL: '회원 가입 실패',
  SIGN_IN_SUCCESS: '로그인 성공',
  SIGN_IN_FAIL: '로그인 실패',
  ALREADY_ID: '존재하는 ID 입니다.',
  NO_USER: '존재하지 않는 유저 id 입니다.',
  MISS_MATCH: '비밀번호 혹은 이메일이 일치하지 않습니다',
  EMPTY_TOKEN: '토큰이 없습니다',
  USER_READ_SUCCESS: '유저 조회 성공',
  USER_DELETE_SUCCESS: '유저 정보 삭제 완료',
  USER_UPDATE_SUCCESS: '유저 정보 업데이트 완료',
  PASSWORD_RESET_SUCCESS: '비밀번호 초기화 완료',
  PASSWORD_UPDATE_SUCCESS: '비밀번호 재설정 완료',
  DB_ERROR: '데이터베이스 오류',
  EMPTY_EMAIL: '아이디를 입력해주세요',
  BOARD_CREATE_SUCCESS: '게시글 작성 성공',
  BOARD_CREATE_FAIL: '게시글 작성 실패',
  BOARD_READ_ALL_SUCCESS: '게시글 전체 조회 성공',
  BOARD_READ_ALL_FAIL: '게시글 전체 조회 실패',
  BOARD_READ_SUCCESS: '게시글 조회 성공',
  BOARD_READ_FAIL: '게시글 조회 실패',
  BOARD_UPDATE_SUCCESS: '게시글 수정 성공',
  BOARD_UPDATE_FAIL: '게시글 수정 실패',
  BOARD_DELETE_SUCCESS: '게시글 삭제 성공',
  BOARD_DELETE_FAIL: '게시글 삭제 실패',
  BOARD_ACTIVATE_SUCCESS: '게시글 마감설정 변경 성공',
  BOARD_ACTIVATE_FAIL: '게시글 마감설정 변경 실패',
  ALREADY_ID: '존재하는 ID 입니다.',
  NO_USER: '존재하지 않는 유저 입니다.',
  NO_BOARD: '존재하지 않은 게시글 입니다.',
  MISS_MATCH_PW: '비밀번호가 일치하지 않습니다',
  MISS_MATCH_ID: '현재 유저는 해당 게시물의 글쓴이가 아닙니다',
  INTERNAL_SERVER_ERROR: '서버 내부 오류',
  INVALID_TOKEN: '올바르지 않은 토큰',
};

export default responseMessage;
